export const skillSuggestions = [
    // Frontend
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "Angular",
    "Svelte",
    "SvelteKit",
    "Astro",
    "jQuery",
    "Bootstrap",
    "Tailwind CSS",
    "Material UI",
    "Chakra UI",
    "Ant Design",
    "Shadcn UI",
    "Redux",
    "Redux Toolkit",
    "Zustand",
    "React Query",
    "GSAP",
    "Framer Motion",

    // Backend
    "Node.js",
    "Express.js",
    "NestJS",
    "Django",
    "Flask",
    "FastAPI",
    "Laravel",
    "PHP",
    "Ruby on Rails",
    "ASP.NET",
    "Java",
    "Spring Boot",
    "C#",
    "C++",

    // Databases
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "Redis",
    "Firebase",
    "Supabase",
    "Prisma",
    "Mongoose",

    // Mobile
    "React Native",
    "Flutter",
    "Dart",
    "Swift",
    "SwiftUI",
    "Kotlin",
    "Android Development",
    "iOS Development",

    // UI/UX & Design
    "UI/UX Design",
    "Figma",
    "Adobe XD",
    "Sketch",
    "Photoshop",
    "Illustrator",
    "Adobe After Effects",
    "Adobe Premiere Pro",
    "Canva",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "User Research",

    // DevOps & Cloud
    "Git",
    "GitHub",
    "GitLab",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "AWS",
    "Microsoft Azure",
    "Google Cloud",
    "Vercel",
    "Netlify",
    "Linux",
    "Nginx",

    // APIs & Web
    "REST API",
    "GraphQL",
    "WebSockets",
    "Socket.IO",
    "JWT",
    "OAuth",
    "Web Development",
    "API Integration",
    "Web Scraping",

    // AI & Data
    "Python",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Data Science",
    "Data Analysis",
    "Pandas",
    "NumPy",
    "TensorFlow",
    "PyTorch",
    "OpenAI API",
    "Generative AI",
    "ChatGPT API",

    // E-commerce
    "Shopify",
    "WooCommerce",
    "WordPress",
    "Magento",
    "Webflow",
    "Wix",
    "E-commerce Development",
    "Payment Gateway Integration",
    "PayPal",
    "Stripe",

    // Marketing
    "Digital Marketing",
    "SEO",
    "SEM",
    "Social Media Marketing",
    "Content Marketing",
    "Email Marketing",
    "Google Ads",
    "Facebook Ads",
    "Instagram Marketing",
    "TikTok Marketing",
    "Lead Generation",
    "Affiliate Marketing",

    // Content
    "Content Writing",
    "Copywriting",
    "Technical Writing",
    "Blog Writing",
    "Article Writing",
    "Ghostwriting",
    "Translation",
    "Proofreading",
    "Editing",

    // Video & Motion
    "Video Editing",
    "Motion Graphics",
    "2D Animation",
    "3D Animation",
    "Blender",
    "Cinema 4D",
    "DaVinci Resolve",
    "Video Production",
    "YouTube Video Editing",

    // Graphic Design
    "Graphic Design",
    "Logo Design",
    "Brand Identity",
    "Branding",
    "Social Media Design",
    "Poster Design",
    "Flyer Design",
    "Business Card Design",
    "Packaging Design",
    "Typography",
    "Illustration",

    // Business
    "Business Consulting",
    "Business Analysis",
    "Project Management",
    "Product Management",
    "Virtual Assistance",
    "Data Entry",
    "Customer Support",
    "Microsoft Excel",
    "Microsoft Word",
    "PowerPoint",

    // Other
    "Cybersecurity",
    "Ethical Hacking",
    "QA Testing",
    "Software Testing",
    "Manual Testing",
    "Automation Testing",
    "Selenium",
    "Cypress",
    "Playwright",
    "Game Development",
    "Unity",
    "Unreal Engine",
    "Blockchain",
    "Web3",
    "Smart Contracts",
    "Solidity",
];