export const languages = [
{ name: "Arabic", code: "ar" },
{ name: "English", code: "en" },
{ name: "French", code: "fr" },
{ name: "Spanish", code: "es" },
{ name: "German", code: "de" },
{ name: "Italian", code: "it" },
{ name: "Portuguese", code: "pt" },
{ name: "Russian", code: "ru" },
{ name: "Chinese", code: "zh" },
{ name: "Japanese", code: "ja" },
{ name: "Korean", code: "ko" },
{ name: "Hindi", code: "hi" },
{ name: "Urdu", code: "ur" },
{ name: "Turkish", code: "tr" },
{ name: "Persian", code: "fa" },
{ name: "Hebrew", code: "he" },
{ name: "Dutch", code: "nl" },
{ name: "Polish", code: "pl" },
{ name: "Ukrainian", code: "uk" },
{ name: "Greek", code: "el" },
{ name: "Swedish", code: "sv" },
{ name: "Norwegian", code: "no" },
{ name: "Danish", code: "da" },
{ name: "Finnish", code: "fi" },
{ name: "Czech", code: "cs" },
{ name: "Slovak", code: "sk" },
{ name: "Hungarian", code: "hu" },
{ name: "Romanian", code: "ro" },
{ name: "Bulgarian", code: "bg" },
{ name: "Serbian", code: "sr" },
{ name: "Croatian", code: "hr" },
{ name: "Slovenian", code: "sl" },
{ name: "Bosnian", code: "bs" },
{ name: "Albanian", code: "sq" },
{ name: "Macedonian", code: "mk" },
{ name: "Estonian", code: "et" },
{ name: "Latvian", code: "lv" },
{ name: "Lithuanian", code: "lt" },
{ name: "Icelandic", code: "is" },
{ name: "Irish", code: "ga" },
{ name: "Welsh", code: "cy" },
{ name: "Basque", code: "eu" },
{ name: "Catalan", code: "ca" },
{ name: "Galician", code: "gl" },
{ name: "Georgian", code: "ka" },
{ name: "Armenian", code: "hy" },
{ name: "Azerbaijani", code: "az" },
{ name: "Kazakh", code: "kk" },
{ name: "Uzbek", code: "uz" },
{ name: "Turkmen", code: "tk" },
{ name: "Kyrgyz", code: "ky" },
{ name: "Tajik", code: "tg" },
{ name: "Mongolian", code: "mn" },
{ name: "Bengali", code: "bn" },
{ name: "Punjabi", code: "pa" },
{ name: "Gujarati", code: "gu" },
{ name: "Marathi", code: "mr" },
{ name: "Tamil", code: "ta" },
{ name: "Telugu", code: "te" },
{ name: "Kannada", code: "kn" },
{ name: "Malayalam", code: "ml" },
{ name: "Nepali", code: "ne" },
{ name: "Sinhala", code: "si" },
{ name: "Thai", code: "th" },
{ name: "Vietnamese", code: "vi" },
{ name: "Indonesian", code: "id" },
{ name: "Malay", code: "ms" },
{ name: "Filipino", code: "fil" },
{ name: "Swahili", code: "sw" },
{ name: "Amharic", code: "am" },
{ name: "Somali", code: "so" },
{ name: "Hausa", code: "ha" },
{ name: "Yoruba", code: "yo" },
{ name: "Igbo", code: "ig" },
{ name: "Zulu", code: "zu" },
{ name: "Afrikaans", code: "af" },
{ name: "Xhosa", code: "xh" },
{ name: "Malagasy", code: "mg" },
{ name: "Latin", code: "la" },
{ name: "Esperanto", code: "eo" },
];
export const languageLevels = [
"Basic",
"Conversational",
"Intermediate",
"Fluent",
"Professional",
"Native",
];