export const specialtyOptions = [
'Web Development',
'Mobile Development',
'Software Development',
'UI/UX Design',
'Graphic Design',
'Writing & Content',
'Translation',
'Digital Marketing',
'SEO',
'Social Media Marketing',
'Video & Animation',
'Photography',
'Data & Analytics',
'AI & Machine Learning',
'Business & Consulting',
'Accounting & Finance',
'Customer Support',
'Virtual Assistance',
'Engineering & Architecture',
'Education & Tutoring',
];